FROM ubuntu:22.04

ENV USER someuser

RUN apt-get update \
  && apt-get install -y \
        curl wget \
        sudo \
        git \
        zsh \
  && rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/zsh ${USER} && \
    usermod -aG sudo ${USER} && \
    echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER ${USER}
ENV HOME /home/${USER}
WORKDIR ${HOME}
